DROP DATABASE IF EXISTS c2;
CREATE DATABASE c2;
USE c2;

CREATE TABLE ANIMAL_INS(
ANIMAL_ID	VARCHAR(60)	NOT NULL
ANIMAL_TYPE	VARCHAR(60)	NOT NULL
`DATETIME`	DATETIME	NOT NULL
INTAKE_CONDITION	VARCHAR(60)	NOT NULL
`NAME`	VARCHAR(60)
SEX_UPON_INTAKE	VARCHAR(60)	NOT NULL
);

