DROP DATABASE IF EXISTS e1;
CREATE DATABASE e1;
USE e1;

CREATE TABLE `TABLE1`(
TR_NO INT,
USER_ID INT,
AMT  INT);

CREATE TABLE `TABLE2`(
TR_NO INT,
USER_ID INT,
AMT  INT);

CREATE TABLE `TABLE3`(
TR_NO INT,
USER_ID INT,
AMT  INT);

SELECT *
FROM TABLE1

INSERT INTO TABLE1 VALUES(1,1,1);
INSERT INTO TABLE1 VALUES(2,2,2);
INSERT INTO TABLE1 VALUES(3,3,3);

INSERT INTO TABLE2 VALUES(1,1,1);
INSERT INTO TABLE2 VALUES(2,2,2);
INSERT INTO TABLE2 VALUES(3,3,3);


INSERT INTO TABLE3 VALUES(1,1,1);
INSERT INTO TABLE3 VALUES(2,2,2);
INSERT INTO TABLE3 VALUES(3,3,3);



SELECT COUNT(sub2.a), SUM(sub2.a), COUNT(sub2.a) FROM
(
    SELECT COUNT(sub1.TR_NO) a, SUM(sub1.AMT) b, COUNT(DISTINCT(sub1.USER_ID)) c
    FROM (
        SELECT TR_NO, USER_ID, AMT FROM TABLE1
        UNION ALL
        SELECT TR_NO, USER_ID, AMT FROM TABLE2
        UNION ALL
        SELECT TR_NO, USER_ID, AMT FROM TABLE3
    )sub1 #별칭 지정 중요!
    GROUP BY USER_ID
)sub2;