DROP DATABASE IF EXISTS c1;
CREATE DATABASE c1;
USE c1;

CREATE TABLE ONLINE_SALE(
ONLINE_SALE_ID	INT	UNSIGNED NOT NULL,
USER_ID	INT NOT NULL,
PRODUCT_ID	INT	NOT NULL,
SALES_AMOUNT INT NOT NULL,
SALES_DATE	DATE NOT NULL
);

CREATE TABLE OFFLINE_SALE(
OFFLINE_SALE_ID	INT NOT NULL,
PRODUCT_ID	INT NOT NULL,
SALES_AMOUNT INT NOT NULL,
SALES_DATE	DATE NOT NULL
);

INSERT INTO ONLINE_SALE VALUES(1,	1,	3,	2,	'2022-02-25');
INSERT INTO ONLINE_SALE VALUES(2,	4,	4,	1,	'2022-03-01');
INSERT INTO ONLINE_SALE VALUES(4,	2,	2,	2,	'2022-03-02');
INSERT INTO ONLINE_SALE VALUES(3,	6,	3,	3,	'2022-03-02');
INSERT INTO ONLINE_SALE VALUES(5,	5,	5,	1,	'2022-03-03');
INSERT INTO ONLINE_SALE VALUES(6,	5,	7,	1,	'2022-04-06');


SELECT *
FROM ONLINE_SALE;



INSERT INTO OFFLINE_SALE VALUES(1,	1,	2,	'2022-02-21');
INSERT INTO OFFLINE_SALE VALUES(4,	1,	2,	'2022-03-01');
INSERT INTO OFFLINE_SALE VALUES(3,	3,	3,	'2022-03-01');
INSERT INTO OFFLINE_SALE VALUES(2,	4,	1,	'2022-03-01');
INSERT INTO OFFLINE_SALE VALUES(5,	2,	1,	'2022-03-03');
INSERT INTO OFFLINE_SALE VALUES(6,	2,	1,	'2022-04-01');

SELECT *
FROM OFFLINE_SALE;


SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID,USER_ID,SALES_AMOUNT  FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT  FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;


/*
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM ONLINE_SALE 
WHERE SALES_DATE >= "2022-03-01" 
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
FROM OFFLINE_SALE 
WHERE SALES_DATE >= "2022-03-01" 
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
*/
#4월 달 값도 포함되기 때문에 안됨

-- 코드를 입력하세요
SELECT *, DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%m')='03'



